Funcionalidad 13/exportar descargar varios egresades
TallerDeDesarrollo-UCB/Nahual-Empresas pull request #21
Opened 2020-10-08 01:40 UTC by FidelRojas

2020-10-08 15:34 UTC, Kuko-CMLC submitted a review, later dismissed

2020-10-08 15:34 UTC, Kuko-CMLC commented on src/Components/GraduatesList/GraduatesList.jsx
> +								(console.log(this.state.egresadesSeleccionados),
Deberiamos quitar este console.log, representa una vulnerabilidad al sistema. :o

2020-10-08 15:35 UTC, JPC07 commented on src/Components/GraduatesList/BotonExportar.jsx
> +        content: cantidad,
Coma innecesaria

2020-10-08 15:35 UTC, JPC07 commented on src/Components/GraduatesList/BotonExportar.jsx
> +    right: { style: "medium", color: { rgb: "66a527" } },
Comma innecesaria

2020-10-08 15:35 UTC, JPC07 commented on src/Components/GraduatesList/BotonExportar.jsx
> +        style: estilos,
Comma innecesaria, revisen los demas campos ya que tienen el mismo formato

2020-10-08 15:35 UTC, JPC07 commented on src/Components/GraduatesList/BotonExportar.jsx
> +    egresade.graduationYear,
Comma innecesaria

2020-10-08 15:35 UTC, JPC07 commented on src/Components/GraduatesList/GraduatesList.jsx
> +			egresadesSeleccionados: [],
Remover comma innecesaria

2020-10-08 15:35 UTC, JPC07 commented on src/Components/GraduatesList/GraduatesList.jsx
> +			displayLoader: false,
Hay algun motivo porque el cuan se agrego la comma? Ya que el anterior version no habia

2020-10-08 15:35 UTC, JPC07 commented on src/Components/GraduatesList/GraduatesList.jsx
> +	cambiarCheckedDeCheckbox(filtro) {
Creo que el nombre esta mezclado entre español e ingles, talves podria ser cambiarEstadoDeCheckbox

2020-10-08 15:35 UTC, JPC07 commented on src/Components/GraduatesList/GraduatesList.jsx
> +							border: "#81ce32 2px solid",
Revisen las commas de todo el archivo, hay muchas commas innecesarias.

2020-10-08 15:35 UTC, JPC07 commented on src/Components/GraduatesList/Graduated.jsx
> +	const seleccionarEgresade = (graduated) => {
el nombre de graduated no seria en español

2020-10-08 18:03 UTC, FidelRojas commented on src/Components/GraduatesList/GraduatesList.jsx
> +								(console.log(this.state.egresadesSeleccionados),
Este log estaba en la rama de "Funcionalidad 95/seleccionar varios egresades", ya se observo y quito de ahí

2020-10-08 20:08 UTC, JPC07 commented on src/Components/GraduatesList/GraduatesList.jsx
> +	cambiarCheckedDeCheckbox(filtro) {
Se arreglo en la rama de funcionalidad 95

2020-10-10 21:53 UTC, JoseCarlosOliveraPeredo commented on src/Components/GraduatesList/BotonExportar.jsx
> +    columns: [
Si es que se puede, seria conveniente cambiar "columns" por "columnas"

2020-10-10 21:53 UTC, JoseCarlosOliveraPeredo commented on src/Components/GraduatesList/BotonExportar.jsx
> +    data: [],
de igual manera si se puede, quiza convendria cambiar "data", por "datos"

2020-10-10 21:53 UTC, JoseCarlosOliveraPeredo commented on src/Components/GraduatesList/BotonExportar.jsx
> +  },
Tengo un par de segurencias

2020-10-10 22:27 UTC, PabloCanelas approved these changes

2020-10-10 23:46 UTC, johancarlos approved these changes

2020-10-11 16:44 UTC, GamalSerhanOporto approved these changes

2020-10-11 17:53 UTC, FidelRojas commented on src/Components/GraduatesList/BotonExportar.jsx
> +    columns: [
no,  es el formato que la librería de exportar necesita.

2020-10-11 21:05 UTC, JPC07 approved these changes

2020-10-11 21:55 UTC, Kuko-CMLC requested changes
Con respecto al momento de exportar el Excel, Depues de exportar no deberian deselecionarse los egresades exportados? y la ultima fila de la tabla excel dice solo "Año", no se si se puede cambiar el nombre por otro mas descriptivo como "Año de Graduacion" si fuera el caso.

2020-10-11 21:55 UTC, Kuko-CMLC commented on src/Components/GraduatesList/BotonExportar.jsx
> +    numero + 1,
Que es numero? es un Iterador? un Id? quizas podriamos darle un nombre mas apropiado dependiendo su funcionalidad.

2020-10-11 22:31 UTC, FidelRojas commented on src/Components/GraduatesList/BotonExportar.jsx
> +    numero + 1,
numero de la lista que aparecerá en el excel, alguna sugerencia de nombre?

2020-10-12 00:19 UTC, Kuko-CMLC commented on src/Components/GraduatesList/BotonExportar.jsx
> +    numero + 1,
Quizas NumeroEnLaLista o EgresadeNro o NroIdExcel

2020-10-12 02:32 UTC, JPC07 approved these changes

2020-10-12 02:32 UTC, merged