Funcionalidad 81/cambiar idioma de codigo fuente
TallerDeDesarrollo-UCB/Nahual-Empresas pull request #22
Opened 2020-10-08 16:01 UTC by GamalSerhanOporto

2020-10-10 23:20 UTC, JPC07 commented on src/Componentes/DetalleDeEgresade/DetalleDeEgresade.jsx
> +        onabierto={() => this.mostrarModal(true)}
Creo que el nombre de este evento, no define bien el concepto ademas que esta mezclado en 2 idiomas, podria ser eventoAbierto u otro nombre que ustedes vean conveniente.

2020-10-10 23:21 UTC, JPC07 commented on yarn.lock
> +moment@^2.28.0:
Remover paquete

2020-10-10 23:23 UTC, JPC07 commented on src/Componentes/ListaEgresades/ListaEgresades.jsx
> +									<FilterButton manejar={this.manejar} />
Podria ser manejarEvento, ya que creo que solo manejar no suena bien, es un poco ambiguo

2020-10-10 23:30 UTC, JPC07 commented on src/Componentes/DetalleDeEgresade/CuerpoModal.jsx
> +import PersonalInformation from "./InformacionPersonal";
No deberia ser InformacionPersonal???, creo que daria error, por el momento no puedo probar esa parte debido a las APIs

2020-10-10 23:31 UTC, JPC07 commented on src/Componentes/DetalleDeEgresade/CuerpoModal.jsx
> +import CoursesInformation from "./InformacionDeCursos";
No deberia ser InformacionDeCursos???, creo que daria error, por el momento no puedo probar esa parte debido a las APIs

2020-10-10 23:32 UTC, JPC07 commented on src/Componentes/DetalleDeEgresade/CuerpoModal.jsx
> +          <PersonalInformation egresade={egresade} />
Si se cambio a InformacionPersonal no deberia tener lo mismo? Probaron si funcionaba asi ?

2020-10-10 23:33 UTC, JPC07 commented on src/Componentes/DetalleDeEgresade/CuerpoModal.jsx
> +          <CoursesInformation egresade={egresade} />
Tambien este, si se cambio a InformacionDeCursos les corre? Por el momento no pude hacerle la prueba ya que las Apis estan en ingles.

2020-10-10 23:49 UTC, JPC07 commented on src/Componentes/ListaEgresades/ListaEgresades.jsx
> +import FilterButton from "./BotonDeFiltrado";
No deberia ser BotonDeFiltrado y no filterButton?

2020-10-10 23:50 UTC, JPC07 commented on src/Componentes/ListaEgresades/ListaEgresades.jsx
> +									<FilterButton manejar={this.manejar} />
No deberia ser BotonDeFiltrado y no filterButton?

2020-10-10 23:59 UTC, JPC07 commented on src/Componentes/FiltradoEgresades/FabricaDeFiltros/FabricaDeFiltros.jsx
> +      filtrarPorModuloCompletado = ''
Falta indentación

2020-10-10 23:59 UTC, JPC07 commented on src/Componentes/FiltradoEgresades/FabricaDeFiltros/FabricaDeFiltros.jsx
> +      filtrarPorModuloCompletado =`module=${criterioDeFiltrado.value}&`;
Falta indentación, revisar en los demas cases

2020-10-11 00:07 UTC, johancarlos commented on src/Componentes/DetalleDeEgresade/DetalleDeEgresade.jsx
> +      .then(respuesta => {
response no es palabra reservada??? con "respuesta" creo q daria error

2020-10-11 00:13 UTC, johancarlos commented on src/Componentes/DetalleDeEgresade/DetalleDeEgresade.jsx
> +        onabierto={() => this.mostrarModal(true)}
1. Si se esta mezclando idiomas
2. No es descriptivo
3. No estas usando camelCase

2020-10-11 00:17 UTC, johancarlos commented on src/Componentes/DetalleDeEgresade/DetalleDeEgresade.jsx
> +class detalleDeEgresade extends Component {
Dentro de los estandares que estamos usando el nombre de las clases inician con Mayuscula

2020-10-11 00:18 UTC, johancarlos commented on src/Componentes/DetalleDeEgresade/InformacionPersonal.jsx
> +  const fecha_convertida = moment(egresade.birthDate).format('LL');
variable sin formato camelCase

2020-10-11 00:20 UTC, johancarlos commented on src/Componentes/DetalleDeEgresade/InformacionPersonal.jsx
> +function informacionPersonal({ egresade }) {
esta funcion deberia iniciar con mayuscula: InformacionPersonal

2020-10-11 00:23 UTC, johancarlos commented on src/Componentes/FiltradoEgresades/FabricaDeFiltros/FabricaDeFiltros.jsx
> +export default fabricaDeFiltros;
deberia ir como el nombre del archivo iniciando con mayuscula: "FabricaDeFiltros"

2020-10-11 00:24 UTC, johancarlos commented on src/Componentes/FiltradoEgresades/OpcionesDeModulosCompletados.jsx
> +class opcionesDeModulosCompletados extends Component{
Titulo de clase deberia iniciar con mayuscula OpcionesDeModulosCompletados. :)

2020-10-11 00:24 UTC, johancarlos commented on src/Componentes/FiltradoEgresades/OpcionesDeModulosCompletados.jsx
> +		this.state = {
linea 8 tiene espacios de mas

2020-10-11 00:25 UTC, johancarlos commented on src/Componentes/FiltradoEgresades/OpcionesDeModulosCompletados.jsx
> +      value: '',
no deberia convertirse a español:  "valor"?

2020-10-11 00:27 UTC, johancarlos commented on src/Componentes/FiltradoEgresades/OpcionesDeNivelDeIngles.jsx
> +class opcionesDeNivelDeIngles extends Component{
Titulo de clase inicia con mayuscula, revisar todas porfavor para q no comente una por una! gracias :)

2020-10-11 00:27 UTC, johancarlos commented on src/Componentes/FiltradoEgresades/OpcionesDeNivelDeIngles.jsx
> +		this.state = {
espacio extra en linea 8

2020-10-11 00:30 UTC, JPC07 commented on src/Componentes/FiltradoEgresades/OpcionesDeNivelDeIngles.jsx
> +		this.state = {
Sobre esto no estoy segura, en visual studio me aparece con la indentación correcta. Te aparece a ti de diferente manera @johancarlos ?

2020-10-11 00:30 UTC, JPC07 commented on src/Componentes/FiltradoEgresades/OpcionesDeModulosCompletados.jsx
> +		this.state = {
Sobre esto no estoy segura, en visual studio me aparece con la indentación correcta. Te aparece a ti de diferente manera @johancarlos ?

2020-10-11 00:31 UTC, johancarlos commented on src/Componentes/ListaEgresades/ListaEgresades.jsx
> +		super(props);
verificar cantidad de espacios de identacion

2020-10-11 00:35 UTC, johancarlos reviewed
Les deje un par de comentarios! :) gracias!!

2020-10-11 17:00 UTC, PabloCanelas commented on src/Componentes/DetalleDeEgresade/CuerpoModal.jsx
> +          <CoursesInformation egresade={egresade} />
Si! no hubieron problemas para correr, de todas maneras ya hice la correccion en todos los imports para no tener componentes con nombre en ingles. Gracias!

2020-10-11 17:01 UTC, PabloCanelas commented on src/Componentes/FiltradoEgresades/FabricaDeFiltros/FabricaDeFiltros.jsx
> +      filtrarPorModuloCompletado = ''
Gracias, ya esta corregido!

2020-10-11 17:02 UTC, PabloCanelas commented on src/Componentes/DetalleDeEgresade/DetalleDeEgresade.jsx
> +class detalleDeEgresade extends Component {
Gracias Johan!, ahora todos los componentes fueron corregidos para que empiecen en mayuscula.

2020-10-11 17:03 UTC, PabloCanelas commented on src/Componentes/FiltradoEgresades/OpcionesDeModulosCompletados.jsx
> +		this.state = {
Parece ser algo con como se muestra el codigo en git, lo revisare bien pero no hay ese problema dentro de Visual Code.

2020-10-11 17:34 UTC, JoseCarlosOliveraPeredo reviewed
Tengo pequeñas observaciones, el resto me parece que esta muy bien :)

2020-10-11 17:34 UTC, JoseCarlosOliveraPeredo commented on src/Componentes/FiltradoEgresades/OpcionesDeModulosCompletados.jsx
> +  manejar(opcionSeleccionada){
Sugiero cambiar el nombre de esta funcion ya que no es muy descriptiva.

2020-10-11 17:34 UTC, JoseCarlosOliveraPeredo commented on src/Componentes/FiltradoEgresades/OpcionesDeModulosCompletados.jsx
> +              onClick={() => this.manejar(opcion)}
De igual manera aca, manejar que?

2020-10-11 17:34 UTC, JoseCarlosOliveraPeredo commented on src/Componentes/ListaEgresades/BotonDeFiltrado.jsx
> +        <OpcionesDeNodo manejar={props.manejar}/>
De igual manera aca, sugiero cambiar el nombre de la prop que se le pasa a los componentes

2020-10-11 17:34 UTC, JoseCarlosOliveraPeredo commented on src/Componentes/ListaEgresades/ListaEgresades.jsx
> +		this.obtenerTodesLosEgresades();
Todes?? no seria Todos.

2020-10-11 17:34 UTC, JoseCarlosOliveraPeredo commented on src/Componentes/FiltradoEgresades/OpcionesDeNivelDeIngles.jsx
> +    await ServicioDeFiltrado.obtenerOpcionesDeNivelesDeIngles()
no seria obtenerOpcionesDeNivelDeIngles??

2020-10-12 13:40 UTC, melissafg requested changes

2020-10-12 13:40 UTC, melissafg commented on src/Componentes/FiltradoEgresades/OpcionesDeNodo.jsx
> +    return nodoTodos;
nodoTodos? no suena ni se entiende muy bien, podrían cambiar el nombre :)

2020-10-12 13:41 UTC, melissafg reviewed
solo un comentario.

2020-10-13 12:31 UTC, closed without merging