Funcionalidad 150/login empresas
TallerDeDesarrollo-UCB/Nahual-Empresas pull request #37
Opened 2020-10-24 23:45 UTC by FidelRojas

2020-10-25 15:22 UTC, Kuko-CMLC requested changes, later dismissed

2020-10-25 15:22 UTC, Kuko-CMLC commented on src/App.jsx
> +  const { isAuthenticated } = useAuth0();
isAuthenticated es propio de Auth0? hay la posibilidad de cambiar a  español como "EstaAutenticado"?

2020-10-25 15:22 UTC, Kuko-CMLC commented on src/Componentes/Layouts/Encabezado.jsx
> +  const { user, isAuthenticated, logout } = useAuth0();
Hay la posibilidad de cambiar la parte de "User" a español?

2020-10-25 15:22 UTC, Kuko-CMLC commented on src/Componentes/Paginas/Autenticado.jsx
> +    await Axios.post(`${SERVICIO_DE_VERIFICACION_API_NAHUAL}/verificar`, {
Seria bueno mantener nuestras solicitudes en un archivo de "Servicios" algo como "Athentication serives" || "ServicioDeAutenticacion.jsx" para que sea mas escalable

2020-10-25 15:22 UTC, Kuko-CMLC commented on src/Componentes/Paginas/IniciarSesion.jsx
> +        Bienvenido!
Deberia ser ¡Bienvenido!

2020-10-25 15:22 UTC, Kuko-CMLC commented on .env.local
> +REACT_APP_SOLICITAR_ACCESO_URL = http://localhost:3001
Supongo que esta URL debe de ser cambiada a futuro con la APP deployada.

2020-10-25 15:22 UTC, Kuko-CMLC commented on src/Componentes/Paginas/Autenticado.jsx
> +        //this.errorDeCaptura(error);
Quitar este comentario y colocar un Alert por ahora como no manejamos todavia modals de excepciones.

2020-10-25 15:22 UTC, Kuko-CMLC commented on src/Componentes/Paginas/Autenticado.jsx
> +
Espacio innecesario

2020-10-25 15:22 UTC, Kuko-CMLC commented on src/Componentes/Paginas/NoAutorizado.jsx
> +  const { user, logout, getIdTokenClaims } = useAuth0();
Pasa lo mismo con otros nombres de variables, hay la posibilidad de colocarlo en español?

2020-10-25 15:48 UTC, FidelRojas commented on src/App.jsx
> +  const { isAuthenticated } = useAuth0();
Es propio de auth0

2020-10-25 15:48 UTC, FidelRojas commented on src/Componentes/Layouts/Encabezado.jsx
> +  const { user, isAuthenticated, logout } = useAuth0();
Es propio de auth0

2020-10-25 15:52 UTC, FidelRojas commented on src/Componentes/Paginas/Autenticado.jsx
> +    await Axios.post(`${SERVICIO_DE_VERIFICACION_API_NAHUAL}/verificar`, {
creo que eso convendría si tuviéramos mas cosas que poner en el servicio pero es lo único.

2020-10-25 15:53 UTC, FidelRojas commented on src/Componentes/Paginas/IniciarSesion.jsx
> +        Bienvenido!
Corregido

2020-10-25 15:53 UTC, FidelRojas commented on .env.local
> +REACT_APP_SOLICITAR_ACCESO_URL = http://localhost:3001
supones bien.

2020-10-25 15:54 UTC, FidelRojas commented on src/Componentes/Paginas/Autenticado.jsx
> +        //this.errorDeCaptura(error);
ese comentario se quitara cuando el backend este funcionando, como se explico en WhatsApp

2020-10-25 15:56 UTC, FidelRojas commented on src/Componentes/Paginas/Autenticado.jsx
> +
Corregido

2020-10-25 15:57 UTC, FidelRojas commented on src/Componentes/Paginas/NoAutorizado.jsx
> +  const { user, logout, getIdTokenClaims } = useAuth0();
No, son propios de auth0

2020-10-25 18:23 UTC, melissafg reviewed
Cambiar algunos textos :D

2020-10-25 18:23 UTC, melissafg commented on src/Componentes/Paginas/IniciarSesion.jsx
> +          Es bueno tenerte acá, para poder continuar debes:
"es bueno tenerte aquí " no suena mejor que "acá"?

2020-10-25 18:23 UTC, melissafg commented on src/Componentes/Paginas/NoAutorizado.jsx
> +        subheader="No tienes acceso para ingresar a esta página, tienes la siguientes opciones:"
debería ser "tienes las siguientes" falta una "s"

2020-10-25 18:23 UTC, melissafg commented on src/Componentes/Paginas/NoAutorizado.jsx
> +                content="Si ya solicitaste acceso, no vuelva a hacerlo, su solicitud esta siendo procesada."
debería ser "no vuelvas a hacerlo" (:

2020-10-25 23:05 UTC, JPC07 commented on src/Componentes/Paginas/IniciarSesion.jsx
> +        !Bienvenido!
No seria al reves el signo de exclamación? - >  "¡"

2020-10-25 23:07 UTC, JPC07 commented on src/Componentes/Paginas/NoAutorizado.jsx
> +    var ecriptado = AES.encrypt(JSON.stringify(datos), CLAVE);
Creo que falta una n para que sea encriptado

2020-10-26 20:57 UTC, PabloCanelas approved these changes

2020-10-26 21:23 UTC, GamalSerhanOporto approved these changes

2020-10-27 04:44 UTC, merged