Funcionalidad 119/refinar cambio de idioma
TallerDeDesarrollo-UCB/Nahual-Empresas pull request #41
Opened 2020-11-04 15:53 UTC by PabloCanelas

2020-11-05 13:36 UTC, JPC07 commented on src/Componentes/FiltradoDeEgresades/OpcionesDeModulosCompletados.jsx
>          key: opcionDeModuloCompletado.id,
no se tendria que cambiar tambien el key y text? como lo hicieron para value y filterby?

2020-11-05 13:36 UTC, JPC07 commented on src/Componentes/FiltradoDeEgresades/OpcionesDeNivelDeIngles.jsx
>      this.setState({opcionesDeFiltrado :opcionesDeNivelDeIngles})
Los ':' deberian estar al lado de opciones de filtrado para darle mejor formato.

2020-11-05 13:36 UTC, JPC07 commented on src/Componentes/FiltradoDeEgresades/OpcionesDeNivelDeIngles.jsx
>          key: opcionDeNivelDeIngles.id,
No se tendria que cambiar tambien el key y text? como se hizo para value y filterby?

2020-11-05 13:36 UTC, JPC07 commented on src/Componentes/FiltradoDeEgresades/OpcionesDeNodo.jsx
>          key: opcionNodo.id,
Lo mismo que la anterior observacion, no se tendria que cambiar tambien el key y text? como lo hicieron para value y filterby?

2020-11-05 13:36 UTC, JPC07 commented on src/Componentes/FiltradoDeEgresades/OpcionesDeQuitarFiltro.jsx
>          text: "Todos",
No deberia ser texto y no text como esta en los otros states, ejemplo modelo completado? El campo key tiene que estar en ingles?

2020-11-05 15:33 UTC, melissafg commented on src/Componentes/FiltradoDeEgresades/OpcionesDeNivelDeIngles.jsx
>      this.setState({opcionesDeFiltrado :opcionesDeNivelDeIngles})
oki lo arreglamos, pero eso era de otra historia ;)

2020-11-05 18:09 UTC, Kuko-CMLC requested changes
No tengo observaciones con respecto al codigo, terminene de corregir la parte de Key y Text como indico Jeymi, despues de ello creo que estaria listo para ser mergeado, buen trabajo.

2020-11-05 18:59 UTC, JoseCarlosOliveraPeredo approved these changes

2020-11-06 17:30 UTC, FidelRojas approved these changes
no tengo mas observaciones de las que ya están.

2020-11-06 23:54 UTC, merged